createOrReplace

	expression DataFolder = "C:\airline-sales-performance-bi\data\model" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]

	table SalesFlown

		column 'DATA TYPE'
			dataType: string
			summarizeBy: none
			sourceColumn: DATA TYPE

		column 'SERVICE TYPE'
			dataType: string
			summarizeBy: none
			sourceColumn: SERVICE TYPE

		column SUBSERVICE
			dataType: string
			summarizeBy: none
			sourceColumn: SUBSERVICE

		column 'AGEN NO'
			dataType: string
			summarizeBy: none
			sourceColumn: AGEN NO

		column 'AGENT GROUPING'
			dataType: string
			summarizeBy: none
			sourceColumn: AGENT GROUPING

		column POI
			dataType: string
			summarizeBy: none
			sourceColumn: POI

		column 'BRANCH OFFICE'
			dataType: string
			summarizeBy: none
			sourceColumn: BRANCH OFFICE

		column ROUTEVV
			dataType: string
			summarizeBy: none
			sourceColumn: ROUTEVV

		column ROUTE
			dataType: string
			summarizeBy: none
			sourceColumn: ROUTE

		column DATES
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: DATES

		column 'CORP CODE'
			dataType: string
			summarizeBy: none
			sourceColumn: CORP CODE

		column 'GROUPING CHANNEL'
			dataType: string
			summarizeBy: none
			sourceColumn: GROUPING CHANNEL

		column SUBCLASS
			dataType: string
			summarizeBy: none
			sourceColumn: SUBCLASS

		column 'BO POO'
			dataType: string
			summarizeBy: none
			sourceColumn: BO POO

		column 'CORP NAME'
			dataType: string
			summarizeBy: none
			sourceColumn: CORP NAME

		column 'CORPORATE CLUSTER'
			dataType: string
			summarizeBy: none
			sourceColumn: CORPORATE CLUSTER

		column 'AGENT NAME'
			dataType: string
			summarizeBy: none
			sourceColumn: AGENT NAME

		column 'CORP SHARE'
			dataType: string
			summarizeBy: none
			sourceColumn: CORP SHARE

		column AREA
			dataType: string
			summarizeBy: none
			sourceColumn: AREA

		column 'DATE TRAVEL'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: DATE TRAVEL

		column PAX
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: PAX

		column 'NETT USD'
			dataType: double
			formatString: #,0
			summarizeBy: sum
			sourceColumn: NETT USD

		column 'BASIC FARE USD'
			dataType: double
			formatString: #,0
			summarizeBy: sum
			sourceColumn: BASIC FARE USD

		column 'WEEK NUM'
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: WEEK NUM

		column 'Route Status' =
				RELATED ( DimRoute[status] )
			summarizeBy: none

		column 'POO Classification' =
				IF ( SalesFlown[BRANCH OFFICE] = SalesFlown[BO POO], "POO", "Non POO" )
			summarizeBy: none

		column 'Corporate Cluster Group' =
				SWITCH (
				    TRUE (),
				    ISBLANK ( SalesFlown[CORPORATE CLUSTER] ), "(Blank)",
				    SalesFlown[CORPORATE CLUSTER] IN { "GOVERNMENT", "SOE" }, "GOVERNMENT & SOE",
				    SalesFlown[CORPORATE CLUSTER] IN { "CHA/TMC", "PRIVATE" }, "PRIVATE",
				    SalesFlown[CORPORATE CLUSTER]
				)
			summarizeBy: none

		partition SalesFlown = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\fact_sales_flown.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"DATA TYPE", type text}, {"SERVICE TYPE", type text}, {"SUBSERVICE", type text}, {"AGEN NO", type text}, {"AGENT GROUPING", type text}, {"POI", type text}, {"BRANCH OFFICE", type text}, {"ROUTEVV", type text}, {"ROUTE", type text}, {"DATES", type date}, {"CORP CODE", type text}, {"GROUPING CHANNEL", type text}, {"SUBCLASS", type text}, {"BO POO", type text}, {"CORP NAME", type text}, {"CORPORATE CLUSTER", type text}, {"AGENT NAME", type text}, {"CORP SHARE", type text}, {"AREA", type text}, {"DATE TRAVEL", type date}, {"PAX", Int64.Type}, {"NETT USD", type number}, {"BASIC FARE USD", type number}, {"WEEK NUM", Int64.Type}}, "en-US")
					in
					    Typed

	table DimCorporate

		column 'CORP CODE'
			dataType: string
			summarizeBy: none
			sourceColumn: CORP CODE

		column CORPORATE_NAME
			dataType: string
			summarizeBy: none
			sourceColumn: CORPORATE_NAME

		column CORPORATE_CLUSTER
			dataType: string
			summarizeBy: none
			sourceColumn: CORPORATE_CLUSTER

		column INDUSTRY_TYPE
			dataType: string
			summarizeBy: none
			sourceColumn: INDUSTRY_TYPE

		partition DimCorporate = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\dim_corporate.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"CORP CODE", type text}, {"CORPORATE_NAME", type text}, {"CORPORATE_CLUSTER", type text}, {"INDUSTRY_TYPE", type text}}, "en-US")
					in
					    Typed

	table DimBranchRegion

		column BO
			dataType: string
			summarizeBy: none
			sourceColumn: BO

		column REGION
			dataType: string
			summarizeBy: none
			sourceColumn: REGION

		partition DimBranchRegion = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\dim_branch_region.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"BO", type text}, {"REGION", type text}}, "en-US")
					in
					    Typed

	table DimRoute

		column route_vv
			dataType: string
			summarizeBy: none
			sourceColumn: route_vv

		column itinerary
			dataType: string
			summarizeBy: none
			sourceColumn: itinerary

		column dest
			dataType: string
			summarizeBy: none
			sourceColumn: dest

		column service_type
			dataType: string
			summarizeBy: none
			sourceColumn: service_type

		column subservice
			dataType: string
			summarizeBy: none
			sourceColumn: subservice

		column aircraft
			dataType: string
			summarizeBy: none
			sourceColumn: aircraft

		column status
			dataType: string
			summarizeBy: none
			sourceColumn: status

		partition DimRoute = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\dim_route.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"route_vv", type text}, {"itinerary", type text}, {"dest", type text}, {"service_type", type text}, {"subservice", type text}, {"aircraft", type text}, {"status", type text}}, "en-US")
					in
					    Typed

	table BookingPosition

		column RegionCode
			dataType: string
			summarizeBy: none
			sourceColumn: RegionCode

		column FltNbr
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: FltNbr

		column DOW
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: DOW

		column Bulan
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: Bulan

		column FlightType
			dataType: string
			summarizeBy: none
			sourceColumn: FlightType

		column SubServiceCode
			dataType: string
			summarizeBy: none
			sourceColumn: SubServiceCode

		column Tahun
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: Tahun

		column TipeAircraft
			dataType: string
			summarizeBy: none
			sourceColumn: TipeAircraft

		column STD
			dataType: dateTime
			summarizeBy: none
			sourceColumn: STD

		column ServiceTypeCode
			dataType: string
			summarizeBy: none
			sourceColumn: ServiceTypeCode

		column RouteVV
			dataType: string
			summarizeBy: none
			sourceColumn: RouteVV

		column Route
			dataType: string
			summarizeBy: none
			sourceColumn: Route

		column Depart
			dataType: string
			summarizeBy: none
			sourceColumn: Depart

		column Arrived
			dataType: string
			summarizeBy: none
			sourceColumn: Arrived

		column DiffDate
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: DiffDate

		column Book_Total
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: Book_Total

		column Capacity_Total
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: Capacity_Total

		column 'Departure Month' =
				FORMAT ( BookingPosition[STD], "yyyy-mm" )
			summarizeBy: none

		partition BookingPosition = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\fact_booking_position.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"RegionCode", type text}, {"FltNbr", Int64.Type}, {"DOW", Int64.Type}, {"Bulan", Int64.Type}, {"FlightType", type text}, {"SubServiceCode", type text}, {"Tahun", Int64.Type}, {"TipeAircraft", type text}, {"STD", type datetime}, {"ServiceTypeCode", type text}, {"RouteVV", type text}, {"Route", type text}, {"Depart", type text}, {"Arrived", type text}, {"DiffDate", Int64.Type}, {"Book_Total", Int64.Type}, {"Capacity_Total", Int64.Type}}, "en-US")
					in
					    Typed

	table SalesToFlown

		column route_vv
			dataType: string
			summarizeBy: none
			sourceColumn: route_vv

		column servicetypecode
			dataType: string
			summarizeBy: none
			sourceColumn: servicetypecode

		column sales_to_flown
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: sales_to_flown

		column trip_duration
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: trip_duration

		column trip_type
			dataType: string
			summarizeBy: none
			sourceColumn: trip_type

		column year
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: year

		column pax
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: pax

		column 'Trip Duration Group' =
				SWITCH (
				    TRUE (),
				    SalesToFlown[trip_type] = "OW", "One Way",
				    SalesToFlown[trip_duration] <= 3, "1-3 Days",
				    SalesToFlown[trip_duration] <= 7, "4-7 Days",
				    SalesToFlown[trip_duration] <= 14, "8-14 Days",
				    ">14 Days"
				)
			summarizeBy: none
			sortByColumn: 'Trip Duration Sort'

		column 'Trip Duration Sort' =
				SWITCH (
				    TRUE (),
				    SalesToFlown[trip_type] = "OW", 0,
				    SalesToFlown[trip_duration] <= 3, 1,
				    SalesToFlown[trip_duration] <= 7, 2,
				    SalesToFlown[trip_duration] <= 14, 3,
				    4
				)
			summarizeBy: none

		column 'Sales to Flown Group' =
				VAR d = SalesToFlown[sales_to_flown]
				RETURN
				    SWITCH (
				        TRUE (),
				        d = 0, "H",
				        d <= 7, "H-" & d,
				        d <= 30, "H-(8-30)",
				        d <= 60, "H-(31-60)",
				        d <= 120, "H-(61-120)",
				        "H-121+"
				    )
			summarizeBy: none
			sortByColumn: 'Sales to Flown Sort'

		column 'Sales to Flown Sort' =
				VAR d = SalesToFlown[sales_to_flown]
				RETURN
				    SWITCH ( TRUE (), d <= 7, d + 1, d <= 30, 9, d <= 60, 10, d <= 120, 11, 12 )
			summarizeBy: none

		partition SalesToFlown = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\fact_sales_to_flown.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"route_vv", type text}, {"servicetypecode", type text}, {"sales_to_flown", Int64.Type}, {"trip_duration", Int64.Type}, {"trip_type", type text}, {"year", Int64.Type}, {"pax", Int64.Type}}, "en-US")
					in
					    Typed

	table GroupBooking

		column MO
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: MO

		column WEEK
			dataType: int64
			formatString: 0
			summarizeBy: none
			sourceColumn: WEEK

		column 'TGL BOOKING'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: TGL BOOKING

		column PNR
			dataType: string
			summarizeBy: none
			sourceColumn: PNR

		column 'NAMA GROUP'
			dataType: string
			summarizeBy: none
			sourceColumn: NAMA GROUP

		column 'AGENT TRAVEL'
			dataType: string
			summarizeBy: none
			sourceColumn: AGENT TRAVEL

		column 'AGENT/CORP/PRIVATE'
			dataType: string
			summarizeBy: none
			sourceColumn: AGENT/CORP/PRIVATE

		column 'DEPT.DATE'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: DEPT.DATE

		column 'RETURN DATE'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: RETURN DATE

		column ROUTE
			dataType: string
			summarizeBy: none
			sourceColumn: ROUTE

		column DEST
			dataType: string
			summarizeBy: none
			sourceColumn: DEST

		column 'DOM/INT'
			dataType: string
			summarizeBy: none
			sourceColumn: DOM/INT

		column 'TTL PAX'
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: TTL PAX

		column MARKET
			dataType: string
			summarizeBy: none
			sourceColumn: MARKET

		column 'APPROVED SKN FARE - IDR.'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: APPROVED SKN FARE - IDR.

		column YQ
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: YQ

		column 'TAX ++'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: TAX ++

		column 'NETT SALES'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: NETT SALES

		column 'Nett Sales ( basic + yq )'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: Nett Sales ( basic + yq )

		column 'Total sales ( nett x ttl pax )'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: Total sales ( nett x ttl pax )

		column 'FARE BASIC'
			dataType: string
			summarizeBy: none
			sourceColumn: FARE BASIC

		column STATUS
			dataType: string
			summarizeBy: none
			sourceColumn: STATUS

		column 'DATE OF DEPOSIT'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: DATE OF DEPOSIT

		column 'JMLH PAX DEPO'
			dataType: int64
			formatString: #,0
			summarizeBy: sum
			sourceColumn: JMLH PAX DEPO

		column 'JLMH DEPOSIT(idr)'
			dataType: int64
			formatString: #,0
			summarizeBy: none
			sourceColumn: JLMH DEPOSIT(idr)

		column 'REASON CANCEL'
			dataType: string
			summarizeBy: none
			sourceColumn: REASON CANCEL

		column 'CORP CODE'
			dataType: string
			summarizeBy: none
			sourceColumn: CORP CODE

		column 'TIME LIMIT'
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: TIME LIMIT

		column POI
			dataType: string
			summarizeBy: none
			sourceColumn: POI

		column DOI
			dataType: dateTime
			formatString: dd mmm yyyy
			summarizeBy: none
			sourceColumn: DOI

		partition GroupBooking = m
			mode: import
			source =
					let
					    Source = Csv.Document(File.Contents(DataFolder & "\group_bookings.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
					    Typed = Table.TransformColumnTypes(Nulls, {{"MO", Int64.Type}, {"WEEK", Int64.Type}, {"TGL BOOKING", type date}, {"PNR", type text}, {"NAMA GROUP", type text}, {"AGENT TRAVEL", type text}, {"AGENT/CORP/PRIVATE", type text}, {"DEPT.DATE", type date}, {"RETURN DATE", type date}, {"ROUTE", type text}, {"DEST", type text}, {"DOM/INT", type text}, {"TTL PAX", Int64.Type}, {"MARKET", type text}, {"APPROVED SKN FARE - IDR.", Int64.Type}, {"YQ", Int64.Type}, {"TAX ++", Int64.Type}, {"NETT SALES", Int64.Type}, {"Nett Sales ( basic + yq )", Int64.Type}, {"Total sales ( nett x ttl pax )", Int64.Type}, {"FARE BASIC", type text}, {"STATUS", type text}, {"DATE OF DEPOSIT", type date}, {"JMLH PAX DEPO", Int64.Type}, {"JLMH DEPOSIT(idr)", Int64.Type}, {"REASON CANCEL", type text}, {"CORP CODE", type text}, {"TIME LIMIT", type date}, {"POI", type text}, {"DOI", type date}}, "en-US")
					in
					    Typed

	table DateTable
		dataCategory: Time

		column Date
			isKey
			formatString: dd mmm yyyy
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		column Year
			summarizeBy: none
			isNameInferred
			sourceColumn: [Year]

		column Month
			summarizeBy: none
			isNameInferred
			sourceColumn: [Month]
			sortByColumn: MonthNumber

		column MonthNumber
			summarizeBy: none
			isNameInferred
			sourceColumn: [MonthNumber]

		column Quarter
			summarizeBy: none
			isNameInferred
			sourceColumn: [Quarter]

		column 'Day of week name' =
				FORMAT ( DateTable[Date], "ddd" )
			summarizeBy: none
			sortByColumn: 'Day of Week Number'

		column 'Day of Week Number' =
				WEEKDAY ( DateTable[Date], 2 )
			summarizeBy: none

		column WeekNum =
				WEEKNUM ( DateTable[Date], 2 )
			summarizeBy: none

		column YearWeek =
				DateTable[Year] * 100 + DateTable[WeekNum]
			summarizeBy: none

		column 'Month-Day' =
				FORMAT ( DateTable[Date], "MM-DD" )
			summarizeBy: none
			sortByColumn: 'MMDD Numeric'

		column 'MMDD Numeric' =
				MONTH ( DateTable[Date] ) * 100 + DAY ( DateTable[Date] )
			summarizeBy: none

		column 'Date No' =
				DAY ( DateTable[Date] )
			summarizeBy: none

		partition DateTable = calculated
			mode: import
			source =
					ADDCOLUMNS (
					    CALENDAR ( DATE ( 2025, 1, 1 ), DATE ( 2026, 12, 31 ) ),
					    "Year", YEAR ( [Date] ),
					    "Month", FORMAT ( [Date], "MMM" ),
					    "MonthNumber", MONTH ( [Date] ),
					    "Quarter", "Q" & FORMAT ( [Date], "Q" )
					)

	table DateFlown
		dataCategory: Time

		column Date
			isKey
			formatString: dd mmm yyyy
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		column Year
			summarizeBy: none
			isNameInferred
			sourceColumn: [Year]

		column Month
			summarizeBy: none
			isNameInferred
			sourceColumn: [Month]
			sortByColumn: MonthNumber

		column MonthNumber
			summarizeBy: none
			isNameInferred
			sourceColumn: [MonthNumber]

		column Quarter
			summarizeBy: none
			isNameInferred
			sourceColumn: [Quarter]

		column WeekNum =
				WEEKNUM ( DateFlown[Date], 2 )
			summarizeBy: none

		partition DateFlown = calculated
			mode: import
			source =
					ADDCOLUMNS (
					    CALENDAR ( DATE ( 2024, 1, 1 ), DATE ( 2027, 12, 31 ) ),
					    "Year", YEAR ( [Date] ),
					    "Month", FORMAT ( [Date], "MMM" ),
					    "MonthNumber", MONTH ( [Date] ),
					    "Quarter", "Q" & FORMAT ( [Date], "Q" )
					)

	table ValTypeTable

		column SalesType
			summarizeBy: none
			isNameInferred
			sourceColumn: [SalesType]

		partition ValTypeTable = calculated
			mode: import
			source =
					DATATABLE ( "SalesType", STRING, { { "Sales" }, { "Flown" } } )

	table PeriodSelector

		column Period
			summarizeBy: none
			isNameInferred
			sourceColumn: [Period]
			sortByColumn: PeriodSort

		column PeriodSort
			summarizeBy: none
			isNameInferred
			sourceColumn: [PeriodSort]

		partition PeriodSelector = calculated
			mode: import
			source =
					DATATABLE ( "Period", STRING, "PeriodSort", INTEGER, { { "MTD", 1 }, { "YTD", 2 } } )

	table SubclassSortOrder

		column BookingClass
			summarizeBy: none
			isNameInferred
			sourceColumn: [BookingClass]
			sortByColumn: SortOrder

		column SortOrder
			summarizeBy: none
			isNameInferred
			sourceColumn: [SortOrder]

		column Cabin
			summarizeBy: none
			isNameInferred
			sourceColumn: [Cabin]

		column FareFamily
			summarizeBy: none
			isNameInferred
			sourceColumn: [FareFamily]

		partition SubclassSortOrder = calculated
			mode: import
			source =
					DATATABLE (
					    "BookingClass", STRING, "SortOrder", INTEGER, "Cabin", STRING, "FareFamily", STRING,
					    {
					        { "F", 1, "First", "FPA JCDI" }, { "R", 2, "First", "ROX" }, { "P", 3, "First", "FPA JCDI" }, { "A", 4, "First", "FPA JCDI" },
					        { "J", 5, "Business", "FPA JCDI" }, { "C", 6, "Business", "FPA JCDI" }, { "D", 7, "Business", "FPA JCDI" },
					        { "O", 8, "Business", "ROX" }, { "I", 9, "Business", "FPA JCDI" }, { "Z", 10, "Business", "Other" },
					        { "Y", 11, "Economy", "Y" }, { "W", 12, "Economy", "WBMKN" }, { "B", 13, "Economy", "WBMKN" }, { "M", 14, "Economy", "WBMKN" },
					        { "K", 15, "Economy", "WBMKN" }, { "N", 16, "Economy", "WBMKN" }, { "G", 17, "Economy", "Other" }, { "Q", 18, "Economy", "QTV" },
					        { "T", 19, "Economy", "QTV" }, { "V", 20, "Economy", "QTV" }, { "S", 21, "Economy", "SHL" }, { "H", 22, "Economy", "SHL" },
					        { "L", 23, "Economy", "SHL" }, { "E", 24, "Economy", "Other" }, { "U", 25, "Economy", "Other" }, { "X", 26, "Economy", "ROX" }
					    }
					)

	table Calendar_Slicer1

		column Date
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		partition Calendar_Slicer1 = calculated
			mode: import
			source =
					DISTINCT ( SELECTCOLUMNS ( DateTable, "Date", DateTable[Date] ) )

	table Calendar_Slicer2

		column Date
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		partition Calendar_Slicer2 = calculated
			mode: import
			source =
					DISTINCT ( SELECTCOLUMNS ( DateTable, "Date", DateTable[Date] ) )

	table Calendar_Slicer_PO1

		column Date
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		partition Calendar_Slicer_PO1 = calculated
			mode: import
			source =
					DISTINCT ( SELECTCOLUMNS ( DateTable, "Date", DateTable[Date] ) )

	table Calendar_Slicer_PO2

		column Date
			summarizeBy: none
			isNameInferred
			sourceColumn: [Date]

		partition Calendar_Slicer_PO2 = calculated
			mode: import
			source =
					DISTINCT ( SELECTCOLUMNS ( DateTable, "Date", DateTable[Date] ) )

	table _Measures

		measure _MaxDateInData =
				CALCULATE ( MAX ( SalesFlown[DATES] ), ALL ( SalesFlown ) )
			formatString: dd mmm yyyy
			displayFolder: 0 Helpers

		measure _MaxDateInContext =
				MAX ( SalesFlown[DATES] )
			formatString: dd mmm yyyy
			displayFolder: 0 Helpers

		measure _TargetDate =
				[_MaxDateInContext]
			formatString: dd mmm yyyy
			displayFolder: 0 Helpers

		measure _MaxWeek =
				MAX ( SalesFlown[WEEK NUM] )
			formatString: 0
			displayFolder: 0 Helpers

		measure _MaxTravelDateInData =
				CALCULATE ( MAX ( SalesFlown[DATE TRAVEL] ), ALL ( SalesFlown ) )
			formatString: dd mmm yyyy
			displayFolder: 0 Helpers

		measure 'Data As Of' =
				VAR MaxDateInContext = [_MaxDateInContext]
				VAR MaxDateInData = [_MaxDateInData]
				VAR AllMonthsSelected =
				    COUNTROWS ( VALUES ( DateTable[MonthNumber] ) ) = COUNTROWS ( ALL ( DateTable[MonthNumber] ) )
				RETURN
				    IF ( AllMonthsSelected, MaxDateInData, MaxDateInContext )
			formatString: dd mmm yyyy
			displayFolder: 0 Helpers

		measure Revenue =
				SUM ( SalesFlown[NETT USD] )
			formatString: #,0
			displayFolder: 1 Base

		measure Pax =
				SUM ( SalesFlown[PAX] )
			formatString: #,0
			displayFolder: 1 Base

		measure 'Avg Fare' =
				DIVIDE ( [Revenue], [Pax] )
			formatString: #,0
			displayFolder: 1 Base

		measure 'Revenue TY' =
				VAR CutoffDate = [_MaxDateInData]
				RETURN
				    CALCULATE ( [Revenue], KEEPFILTERS ( DateTable[Date] <= CutoffDate ) )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Revenue LY' =
				VAR CutoffDateLY = EDATE ( [_MaxDateInData], -12 )
				RETURN
				    CALCULATE (
				        [Revenue],
				        SAMEPERIODLASTYEAR ( DateTable[Date] ),
				        KEEPFILTERS ( DateTable[Date] <= CutoffDateLY )
				    )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Revenue YoY' =
				[Revenue TY] - [Revenue LY]
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Revenue YoY %' =
				DIVIDE ( [Revenue TY] - [Revenue LY], [Revenue LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 2 TY vs LY

		measure 'Pax TY' =
				VAR CutoffDate = [_MaxDateInData]
				RETURN
				    CALCULATE ( [Pax], KEEPFILTERS ( DateTable[Date] <= CutoffDate ) )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Pax LY' =
				VAR CutoffDateLY = EDATE ( [_MaxDateInData], -12 )
				RETURN
				    CALCULATE (
				        [Pax],
				        SAMEPERIODLASTYEAR ( DateTable[Date] ),
				        KEEPFILTERS ( DateTable[Date] <= CutoffDateLY )
				    )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Pax YoY' =
				[Pax TY] - [Pax LY]
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Pax YoY %' =
				DIVIDE ( [Pax TY] - [Pax LY], [Pax LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 2 TY vs LY

		measure 'Avg Fare TY' =
				DIVIDE ( [Revenue TY], [Pax TY] )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Avg Fare LY' =
				DIVIDE ( [Revenue LY], [Pax LY] )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Avg Fare YoY' =
				[Avg Fare TY] - [Avg Fare LY]
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Avg Fare YoY %' =
				DIVIDE ( [Avg Fare TY] - [Avg Fare LY], [Avg Fare LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 2 TY vs LY

		measure 'Revenue Same Date LY' =
				VAR CurrentDate = MAX ( DateTable[Date] )
				RETURN
				    IF (
				        CurrentDate <= [_MaxDateInData],
				        CALCULATE ( [Revenue], ALL ( DateTable ), DateTable[Date] = EDATE ( CurrentDate, -12 ) )
				    )
			formatString: #,0
			displayFolder: 2 TY vs LY

		measure 'Revenue MTD' =
				VAR TargetDate = [_TargetDate]
				RETURN
				    CALCULATE ( TOTALMTD ( [Revenue], DateTable[Date] ), DateTable[Date] <= TargetDate )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Revenue MTD LY' =
				VAR TargetDateLY = EDATE ( [_TargetDate], -12 )
				RETURN
				    CALCULATE (
				        [Revenue],
				        ALL ( DateTable ),
				        DATESBETWEEN ( DateTable[Date], DATE ( YEAR ( TargetDateLY ), MONTH ( TargetDateLY ), 1 ), TargetDateLY )
				    )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Revenue MTD YoY %' =
				DIVIDE ( [Revenue MTD] - [Revenue MTD LY], [Revenue MTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Revenue YTD' =
				VAR TargetDate = [_TargetDate]
				RETURN
				    CALCULATE ( TOTALYTD ( [Revenue], DateTable[Date] ), DateTable[Date] <= TargetDate )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Revenue YTD LY' =
				VAR TargetDateLY = EDATE ( [_TargetDate], -12 )
				RETURN
				    CALCULATE (
				        [Revenue],
				        ALL ( DateTable ),
				        DATESBETWEEN ( DateTable[Date], DATE ( YEAR ( TargetDateLY ), 1, 1 ), TargetDateLY )
				    )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Revenue YTD YoY %' =
				DIVIDE ( [Revenue YTD] - [Revenue YTD LY], [Revenue YTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Pax MTD' =
				VAR TargetDate = [_TargetDate]
				RETURN
				    CALCULATE ( TOTALMTD ( [Pax], DateTable[Date] ), DateTable[Date] <= TargetDate )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Pax MTD LY' =
				VAR TargetDateLY = EDATE ( [_TargetDate], -12 )
				RETURN
				    CALCULATE (
				        [Pax],
				        ALL ( DateTable ),
				        DATESBETWEEN ( DateTable[Date], DATE ( YEAR ( TargetDateLY ), MONTH ( TargetDateLY ), 1 ), TargetDateLY )
				    )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Pax MTD YoY %' =
				DIVIDE ( [Pax MTD] - [Pax MTD LY], [Pax MTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Pax YTD' =
				VAR TargetDate = [_TargetDate]
				RETURN
				    CALCULATE ( TOTALYTD ( [Pax], DateTable[Date] ), DateTable[Date] <= TargetDate )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Pax YTD LY' =
				VAR TargetDateLY = EDATE ( [_TargetDate], -12 )
				RETURN
				    CALCULATE (
				        [Pax],
				        ALL ( DateTable ),
				        DATESBETWEEN ( DateTable[Date], DATE ( YEAR ( TargetDateLY ), 1, 1 ), TargetDateLY )
				    )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Pax YTD YoY %' =
				DIVIDE ( [Pax YTD] - [Pax YTD LY], [Pax YTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Avg Fare MTD' =
				DIVIDE ( [Revenue MTD], [Pax MTD] )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Avg Fare MTD LY' =
				DIVIDE ( [Revenue MTD LY], [Pax MTD LY] )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Avg Fare MTD YoY %' =
				DIVIDE ( [Avg Fare MTD] - [Avg Fare MTD LY], [Avg Fare MTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Avg Fare YTD' =
				DIVIDE ( [Revenue YTD], [Pax YTD] )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Avg Fare YTD LY' =
				DIVIDE ( [Revenue YTD LY], [Pax YTD LY] )
			formatString: #,0
			displayFolder: 3 MTD YTD

		measure 'Avg Fare YTD YoY %' =
				DIVIDE ( [Avg Fare YTD] - [Avg Fare YTD LY], [Avg Fare YTD LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 3 MTD YTD

		measure 'Revenue Selected Period' =
				SWITCH (
				    SELECTEDVALUE ( PeriodSelector[Period], "MTD" ),
				    "MTD", [Revenue MTD],
				    "YTD", [Revenue YTD]
				)
			formatString: #,0
			displayFolder: 4 Period Switch

		measure 'Revenue Selected Period LY' =
				SWITCH (
				    SELECTEDVALUE ( PeriodSelector[Period], "MTD" ),
				    "MTD", [Revenue MTD LY],
				    "YTD", [Revenue YTD LY]
				)
			formatString: #,0
			displayFolder: 4 Period Switch

		measure 'Revenue Selected Period YoY' =
				[Revenue Selected Period] - [Revenue Selected Period LY]
			formatString: #,0
			displayFolder: 4 Period Switch

		measure 'Revenue Selected Period YoY %' =
				DIVIDE ( [Revenue Selected Period] - [Revenue Selected Period LY], [Revenue Selected Period LY] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 4 Period Switch

		measure 'Revenue P1' =
				CALCULATE (
				    SUM ( SalesFlown[NETT USD] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer1[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Pax P1' =
				CALCULATE (
				    SUM ( SalesFlown[PAX] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer1[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Revenue P2' =
				CALCULATE (
				    SUM ( SalesFlown[NETT USD] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer2[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Pax P2' =
				CALCULATE (
				    SUM ( SalesFlown[PAX] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer2[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Avg Fare P1' =
				DIVIDE ( [Revenue P1], [Pax P1] )
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Avg Fare P2' =
				DIVIDE ( [Revenue P2], [Pax P2] )
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Revenue P2 vs P1' =
				[Revenue P2] - [Revenue P1]
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Revenue P2 vs P1 %' =
				DIVIDE ( [Revenue P2] - [Revenue P1], [Revenue P1] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 5 Period vs Period

		measure 'Pax P2 vs P1' =
				[Pax P2] - [Pax P1]
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Pax P2 vs P1 %' =
				DIVIDE ( [Pax P2] - [Pax P1], [Pax P1] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 5 Period vs Period

		measure 'Avg Fare P2 vs P1 %' =
				DIVIDE ( [Avg Fare P2] - [Avg Fare P1], [Avg Fare P1] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 5 Period vs Period

		measure 'Revenue PO P1' =
				CALCULATE (
				    SUM ( SalesFlown[NETT USD] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer_PO1[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Pax PO P1' =
				CALCULATE (
				    SUM ( SalesFlown[PAX] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer_PO1[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Revenue PO P2' =
				CALCULATE (
				    SUM ( SalesFlown[NETT USD] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer_PO2[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Pax PO P2' =
				CALCULATE (
				    SUM ( SalesFlown[PAX] ),
				    KEEPFILTERS ( TREATAS ( VALUES ( Calendar_Slicer_PO2[Date] ), DateTable[Date] ) )
				)
			formatString: #,0
			displayFolder: 5 Period vs Period

		measure 'Revenue PO P2 vs P1 %' =
				DIVIDE ( [Revenue PO P2] - [Revenue PO P1], [Revenue PO P1] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 6 Pull Out

		measure 'Pax PO P2 vs P1 %' =
				DIVIDE ( [Pax PO P2] - [Pax PO P1], [Pax PO P1] )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 6 Pull Out

		measure 'Pull Out Revenue Recaptured %' =
				VAR LostOnPulledRoutes =
				    CALCULATE ( [Revenue PO P1] - [Revenue PO P2], DimRoute[status] = "Pull Out" )
				VAR GainOnActiveRoutes =
				    CALCULATE ( [Revenue PO P2] - [Revenue PO P1], DimRoute[status] = "Active" )
				RETURN
				    DIVIDE ( GainOnActiveRoutes, LostOnPulledRoutes )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 6 Pull Out

		measure 'Domestic %' =
				DIVIDE (
				    CALCULATE ( [Revenue TY], SalesFlown[SERVICE TYPE] = "DOM" ),
				    CALCULATE ( [Revenue TY], REMOVEFILTERS ( SalesFlown[SERVICE TYPE] ) )
				)
			formatString: 0%
			displayFolder: 7 Mix

		measure 'International %' =
				DIVIDE (
				    CALCULATE ( [Revenue TY], SalesFlown[SERVICE TYPE] = "INT" ),
				    CALCULATE ( [Revenue TY], REMOVEFILTERS ( SalesFlown[SERVICE TYPE] ) )
				)
			formatString: 0%
			displayFolder: 7 Mix

		measure 'Corporate Revenue TY' =
				CALCULATE ( [Revenue TY], SalesFlown[CORP SHARE] = "Corp" )
			formatString: #,0
			displayFolder: 7 Mix

		measure 'Corporate Revenue LY' =
				CALCULATE ( [Revenue LY], SalesFlown[CORP SHARE] = "Corp" )
			formatString: #,0
			displayFolder: 7 Mix

		measure 'Corporate Share %' =
				DIVIDE (
				    CALCULATE ( [Revenue TY], SalesFlown[CORP SHARE] = "Corp" ),
				    CALCULATE ( [Revenue TY], REMOVEFILTERS ( SalesFlown[CORP SHARE] ) )
				)
			formatString: 0%
			displayFolder: 7 Mix

		measure 'Fare Family Share %' =
				DIVIDE ( [Revenue TY], CALCULATE ( [Revenue TY], REMOVEFILTERS ( SubclassSortOrder ) ) )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'FPA JCDI %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "FPA JCDI" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'ROX %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "ROX" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'Y %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "Y" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'WBMKN %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "WBMKN" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'QTV %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "QTV" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'SHL %' =
				CALCULATE ( [Fare Family Share %], SubclassSortOrder[FareFamily] = "SHL" )
			formatString: 0%
			displayFolder: 7 Mix

		measure 'Pax by Travel Date TY' =
				VAR CutoffDate = [_MaxTravelDateInData]
				RETURN
				    CALCULATE ( [Pax], KEEPFILTERS ( DateFlown[Date] <= CutoffDate ) )
			formatString: #,0
			displayFolder: 8 Travel Date

		measure 'Pax by Travel Date LY' =
				VAR CutoffDateLY = EDATE ( [_MaxTravelDateInData], -12 )
				RETURN
				    CALCULATE (
				        [Pax],
				        SAMEPERIODLASTYEAR ( DateFlown[Date] ),
				        KEEPFILTERS ( DateFlown[Date] <= CutoffDateLY )
				    )
			formatString: #,0
			displayFolder: 8 Travel Date

		measure 'Pax by Travel Date YoY %' =
				DIVIDE ( [Pax by Travel Date TY] - [Pax by Travel Date LY], [Pax by Travel Date LY] )
			formatString: 0%
			displayFolder: 8 Travel Date

		measure '% of Total Pax (Lead Time)' =
				DIVIDE ( SUM ( SalesToFlown[pax] ), CALCULATE ( SUM ( SalesToFlown[pax] ), ALLSELECTED () ) )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 9 Lead Time & BLF

		measure 'Avg Lead Time (days)' =
				DIVIDE (
				    SUMX ( SalesToFlown, SalesToFlown[sales_to_flown] * SalesToFlown[pax] ),
				    SUM ( SalesToFlown[pax] )
				)
			formatString: 0.0
			displayFolder: 9 Lead Time & BLF

		measure 'BLF %' =
				DIVIDE ( SUM ( BookingPosition[Book_Total] ), SUM ( BookingPosition[Capacity_Total] ) )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 9 Lead Time & BLF

		measure 'Seats Unsold' =
				SUM ( BookingPosition[Capacity_Total] ) - SUM ( BookingPosition[Book_Total] )
			formatString: #,0
			displayFolder: 9 Lead Time & BLF

		measure 'Group Pax Confirmed' =
				CALCULATE ( SUM ( GroupBooking[TTL PAX] ), GroupBooking[STATUS] IN { "TICKETED", "DEPOSIT" } )
			formatString: #,0
			displayFolder: 10 Group Booking

		measure 'Group Sales IDR' =
				CALCULATE ( SUM ( GroupBooking[Total sales ( nett x ttl pax )] ), GroupBooking[STATUS] IN { "TICKETED", "DEPOSIT" } )
			formatString: #,0
			displayFolder: 10 Group Booking

		measure 'Group Cancel Rate %' =
				DIVIDE ( CALCULATE ( COUNTROWS ( GroupBooking ), GroupBooking[STATUS] = "CANCELLED" ), COUNTROWS ( GroupBooking ) )
			formatString: 0.0%;-0.0%;0.0%
			displayFolder: 10 Group Booking

		column Placeholder
			isHidden
			summarizeBy: none
			isNameInferred
			sourceColumn: [Placeholder]

		partition _Measures = calculated
			mode: import
			source =
					ROW ( "Placeholder", BLANK () )

	relationship SalesFlown_DATES_to_DateTable
		fromColumn: SalesFlown.DATES
		toColumn: DateTable.Date

	relationship SalesFlown_DATE_TRAVEL_to_DateFlown
		fromColumn: SalesFlown.'DATE TRAVEL'
		toColumn: DateFlown.Date

	relationship SalesFlown_DATA_TYPE_to_ValTypeTable
		fromColumn: SalesFlown.'DATA TYPE'
		toColumn: ValTypeTable.SalesType

	relationship SalesFlown_SUBCLASS_to_SubclassSortOrder
		fromColumn: SalesFlown.SUBCLASS
		toColumn: SubclassSortOrder.BookingClass

	relationship SalesFlown_CORP_CODE_to_DimCorporate
		fromColumn: SalesFlown.'CORP CODE'
		toColumn: DimCorporate.'CORP CODE'

	relationship SalesFlown_BRANCH_OFFICE_to_DimBranchRegion
		fromColumn: SalesFlown.'BRANCH OFFICE'
		toColumn: DimBranchRegion.BO

	relationship SalesFlown_ROUTEVV_to_DimRoute
		fromColumn: SalesFlown.ROUTEVV
		toColumn: DimRoute.route_vv

	relationship BookingPosition_RouteVV_to_DimRoute
		fromColumn: BookingPosition.RouteVV
		toColumn: DimRoute.route_vv

	relationship SalesToFlown_route_vv_to_DimRoute
		fromColumn: SalesToFlown.route_vv
		toColumn: DimRoute.route_vv
